dist: focal
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: VKaknfr/1JUbQNZKkT9YeOk4g4zZSDYl4dmB2dB+hlAIjyad0hMtCaeKy1QpEJDEM4BCVfJbjadu7Yut+ESdH90+QI9PbDFxHaAeJVTTaRTdC9q6SLKd2mEWSWv80UpgZu2jupSr7H8ghOvd2v1PjjpD0hZ5t0MgKigcHMv+YG2++rvC3vbsQEPrzuAcYU/Dl6iD/zN1UOikzgRtC/mD7UO8JgStQRFO/WWuYtQRkmylHapxxa/HLRihayWdfez/P/z+IZVVN42oewyl9uMKJDTTfSue1Hf3BMC3yZ1gxN9M0eOw6xwPTq0m8nJB2SM09+Pxw4IZGbVsRLuoU4/2TO9ySRtLdW3erML54YWKvndcwcdoBNcI06bNUf2dLtCP9+gbK0FC2f5/YwavL7agkmku2ktgcGfAkkGReLkcbJ8xck1NAm/TUUWVOsdlVsuTwUDmNsta/ejqaK8zNEXJ10izVSujUG9ka9Hl0NyXci3zA1dfdwZlUFh9l31r+EdSaxdxSnkXLRW+KQo6nQtr2pW9NP+WWBIYoB6eRTilytbbx4oX4DoVcYVyTSeLN2C35g6mnply20hyQ+41jOggvwiwOU8DQqOvNy5Nm9xQV/A4c+4QxwoW7z1/qwXm47C/snxx4spILrXIiRadA1NwfIvg1+rNIaQmfy/0V3GCOuY=
